### ISSUE TITLE
反馈：一直卡在 Deploying状态下

### ISSUE THREAD

**Issue by msghost** [malaohu/Arukas-API#2]
上午看到关于对SSR的回复就一直在测试老版本，部署不成功。
下午看到有新版本了，按使用说明进行了配置，一直卡在Deploying，重复试了几次都这样。
截图反馈配置情况
![default](https://user-images.githubusercontent.com/16555025/26917294-4d79fc6a-4c60-11e7-8e6a-4df4cd471873.png)

**Comment by malaohu** [comment]
arukas.io 不稳定。建议使用DaoCloud部署一下。
