### ISSUE TITLE
SSR订阅服务器地址问题

### ISSUE THREAD

**Issue by snquentin** [malaohu/Arukas-API#3]
ssr订阅服务器地址，在PC端正常订阅，但是在android端无法添加。具体是为什么暂时还不清楚，等待验证！

**Comment by malaohu** [comment]
安卓还不支持。
请关注：https://github.com/breakwa11/shadowsocks-rss/wiki/Subscribe-%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%AE%A2%E9%98%85%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3
