### ISSUE TITLE
Subscription生成ssr地址错误

### ISSUE THREAD

**Issue by alexcaoys** [malaohu/Arukas-API#5]
生成的subscription里面的链接没有经过base64处理，无法被android客户端识别。

**Comment by chenmin1992** [comment]
最新的PC端也不可以，SSR C# 4.6.1，链接没有经过base64处理

**Comment by woodsking2** [comment]
已pull requests，imsage改成woodsking2/arukas-api，已修复

**Comment by malaohu** [comment]
已经兼容处理了。
SSR 4.6.0 ，对SSR订阅对 Base64  和 MAX值 有了新的限制，所有导致无法加载。
